### ISSUE TITLE
Error code: R-1 "A Shadow app is already running on this device"

### ISSUE THREAD

**Issue by MichaelTrip** [NicolasGuilloux/blade-shadow-beta#55] opened 2020-04-29 20:29 UTC
**Describe the bug**
When i start the Shadow client after updating from Fedora 31 to Fedora 32 a get a error : R-1 A Shadow app is already running on your pc. I have to devices, my main workstation and my laptop. Both give an error. I will revert my Workstation back to fedora 31 (i created a clonezilla image) so i can still game on Shadow. I will keep my Laptop on Fedora 32 for further testing if this is required by you. I would like to help in any way necessary. 

**System**
 - OS: Fedora
 - OS Version: 32
 - Environment: Gnome 3.36.1
 - Application: AppImage
 - Application Version: Alpha, Beta and Stable

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? yes

**To Reproduce**
Login to client
click on start streaming

**Screenshots**

![Screenshot from 2020-04-29 22-26-40](https://user-images.githubusercontent.com/1826203/80643773-eca9bc00-8a68-11ea-81f3-eaff2cc989d9.png)

**Comment by brandondtb** [comment] 2020-04-30 01:13
I ran into the same issue on Fedora 32 when I tried to download and run the AppImage.

I was able to get the [dockerized version](https://gitlab.com/aar642/shadowcker) to run successfully.

When I first ran it it stalled on "Shadow is ready" loading screen, which was fixed by adding `ENV LIBVA_DRIVER_NAME=i965` to the Dockerfile above the CMD line.

**Comment by lerenn** [comment] 2020-05-01 21:30
I ran also into the same issue on Fedora 32 when upgrading from 31.
I'll try the dockerized version until a workaround is found.

Edit: Cannot log in dockerized version, I'll try another ways...

**Comment by lerenn** [comment] 2020-05-02 10:45
I couldn't log in the dockerized version, so I had to follow [this instruction](https://github.com/docker/for-linux/issues/955#issuecomment-621209236) and changing `nftables` to `iptables` in `/etc/firewalld/firewalld.conf`.

I also had to add `- LIBVA_DRIVER_NAME=i965` in `docker-compose.yml` in the section `environment` (right under `- PULSE_SERVER=unix:/run/user/1000/pulse/native`) as @brandondtb suggested (thanks by the way!).

Then starting it twice (first time was apparently just to set the app) and it works !

**Comment by MichaelTrip** [comment] 2020-05-02 12:54
> I couldn't log in the dockerized version, so I had to follow [this instruction](https://github.com/docker/for-linux/issues/955#issuecomment-621209236) and changing `nftables` to `iptables` in `/etc/firewalld/firewalld.conf`.
> 
> I also had to add `- LIBVA_DRIVER_NAME=i965` in `docker-compose.yml` in the section `environment` (right under `- PULSE_SERVER=unix:/run/user/1000/pulse/native`) as @brandondtb suggested (thanks by the way!).
> 
> Then starting it twice (first time was apparently just to set the app) and it works !

Thanks mate. Seem to be working for me also.

**Comment by aarnoud** [comment] 2020-05-12 15:09
reopening as it should be looked for nvidia users without Shadowcker

**Comment by CrystallisedEntertainment** [comment] 2020-05-12 20:21
Also getting this issue and I've been told to "ping" it as I have an NVIDIA GPU:

**System**
 - OS: Fedora 64-bit
 - OS Version: 32
 - Environment: GNOME 3.36.2
 - Application: AppImage
 - Application Version: Stable and Beta versions tested
 - NVIDIA GPU: NVIDIA GeForce GTX 1070 Ti (8GB GDDR5)
 - Web Driver Used: 440.82

**Configuration**
 - The user is in input group Yes
 - The environment uses Xorg - Yes (X11)
 - VA API detects H264 ? And H265 ? - Yes

**Comment by aarnoud** [comment] 2020-05-13 05:33
<img width="635" alt="Fedora_Linux__DVD_live_" src="https://user-images.githubusercontent.com/3198544/81774916-fd881200-94eb-11ea-85c4-7253ebbbf39d.png">
WIP

**Comment by aarnoud** [comment] 2020-05-13 06:14
well it's exactly the same as for 31 so far, on a clean install only libva and librtmp (https://fedora.pkgs.org/32/unitedrpms-x86_64/librtmp-2.4-8.20151223.gitfa8646d.fc32.x86_64.rpm.html) are needed

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 06:25
> well it's exactly the same as for 31 so far, on a clean install only libva and librtmp (https://fedora.pkgs.org/32/unitedrpms-x86_64/librtmp-2.4-8.20151223.gitfa8646d.fc32.x86_64.rpm.html) are needed

I just checked in the Terminal, I already have those dependencies installed, as I suspected as much as it did work in 31 after I figured out the NVIDIA patch workaround.

**Comment by aarnoud** [comment] 2020-05-13 06:50
send results, with Shadow.AppImage & ShadowBeta.AppImage started of :

```find /tmp/.mount* -name '*.so*' -exec ldd {} +```

and returns of :

```curl https://raw.githubusercontent.com/NicolasGuilloux/blade-shadow-beta/master/scripts/report.pl | perl```

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 07:44
> send results, with Shadow.AppImage & ShadowBeta.AppImage started of :
> 
> `find /tmp/.mount* -name '*.so*' -exec ldd {} +`
> 
> and returns of :
> 
> `curl https://raw.githubusercontent.com/NicolasGuilloux/blade-shadow-beta/master/scripts/report.pl | perl`

And done. Interestingly enough (for me anyways) that I thought I would need to be logged in as "root" to access those files, but that turned up with "access denied" where the normal terminal did it fine...

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 07:51
I appear to forgot to post the link to the logs, my bad!
So here is the stable: https://nicolasguilloux.eu/hostbin/1840826100 
And here is the beta: https://nicolasguilloux.eu/hostbin/3222429521

**Comment by aarnoud** [comment] 2020-05-13 08:51
results of the find command please

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 09:05
I honestly don't know how to send it through the returns thing if that thing you suggested doesn't do it. So I'm literally just gonna use pastebin.
Stable: https://pastebin.com/6keh5a8s 
Beta: https://pastebin.com/aaSdEhev

**Comment by aarnoud** [comment] 2020-05-13 09:11
@IAMNOTDEFECTIVE all looks good from here, but you are not generating any logs from the Shadow renderer, which would indicate an lib issue, maybe after all the issue is in Launcher?! hmm, what kind of error you get in launcher now ?

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 09:15
The same error as the original creator is getting in both the Stable and Beta releases: "A Shadow app is already running on this device" with the code "R-1". I know this is false as I'm the only user on this machine and I only open 1 appimage when I want to use Shadow.

![image](https://user-images.githubusercontent.com/65254328/81794204-56fb3b80-9502-11ea-8ff0-aad99a3f78ed.png)

**Comment by aarnoud** [comment] 2020-05-13 09:26
Ok, managed to reproduce, it seems located in the Launcher component, the Renderer seems ok on Fedora 32, keeping you posted :)

**Comment by aarnoud** [comment] 2020-05-13 15:20
seems that in Fedora 32 Launcher can't discuss using IPC with the Renderer, didn't find any workaround for now, it may be down the Blade devs to work on this one sadly...

**Comment by CrystallisedEntertainment** [comment] 2020-05-13 17:04
> seems that in Fedora 32 Launcher can't discuss using IPC with the Renderer, didn't find any workaround for now, it may be down the Blade devs to work on this one sadly...

Chances are then that it will not be fixed anytime soon, as Shadow has never officially supported Fedora, only Ubuntu. Ubuntu ran terribly on this system and stability wasn't much better, so I'm less then keen on resorting to that...

**Comment by Sok00** [comment] 2020-05-14 23:09
Have you tested Manjaro or Arch ?

**Comment by CrystallisedEntertainment** [comment] 2020-05-15 06:31
> Have you tested Manjaro or Arch ?

No, and I wasn't planning to since I've already spent literally hours setting my workstation up just the way I want with all the applications I need to fulfil my work. Installing any other OS would result me fiddling around again for hours trying to get drivers, and certain apps, to work as intended as I don't have more then one drive, and that drive is what Fedora is installed on right now. 

And this is not to mention how stable I found Fedora is with my system, more then I can say about Ubuntu, and I don't really want to jeopardise that...

**Comment by lerenn** [comment] 2020-05-15 06:37
> Have you tested Manjaro or Arch ?

With all due respect, and if I get this right, the problem here is to make the app work on Fedora, in order to avoid distribution switch by users. I understand it could be a way for @IAMNOTDEFECTIVE, but I don't think it's a good solution (because other apps could have the reverse problem. And don't get me wrong, I love those 2 distros too 😉 ).

**Comment by aarnoud** [comment] 2020-05-15 08:25
someone could also try to complete work on Shadowcker to support NVIDIA too in the meantime :)

**Comment by Sok00** [comment] 2020-05-15 13:10
> With all due respect, and if I get this right, the problem here is to make the app work on Fedora, in order to avoid distribution switch by users. I understand it could be a way for @IAMNOTDEFECTIVE, but I don't think it's a good solution (because other apps could have the reverse problem. And don't get me wrong, I love those 2 distros too 😉 ).

but you can compare what is different to find the fault, that was my superior.

**Comment by lerenn** [comment] 2020-05-15 13:13
> > With all due respect, and if I get this right, the problem here is to make the app work on Fedora, in order to avoid distribution switch by users. I understand it could be a way for @IAMNOTDEFECTIVE, but I don't think it's a good solution (because other apps could have the reverse problem. And don't get me wrong, I love those 2 distros too 😉 ).
> 
> but you can compare what is different to find the fault, that was my superior.

Indeed, I haven't thought of that. In this case, a dual boot could help 🙂

**Comment by Aikadil** [comment] 2020-05-21 12:47
Exactly the same issues, with fedora32 in nvidia card.

**Comment by ramirocantu** [comment] 2020-07-07 23:41
I'm having the same issues on Fedora Silverblue 32, using Intel UHD 630 graphics

**Comment by ramirocantu** [comment] 2020-07-08 10:09
Found a convenient work around!
**Be sure to use Xorg, wayland will not work**

For intel integrated graphics:
Dependencies: 
- [ ] libva-intel-driver (below gen8)
- [ ] intel-media-driver (If running gen8+) 
- [ ] librtmp  
- [ ] libva-utils (optional, good for debugging with vainfo)

This was tested on a gen10 cometlake thus I used intel-media-driver.

Once you get those packages installed (you will need to use rpm-fussion) run vainfo to make sure everything is nice and ok. should look something like [this](https://pastebin.com/8i5gPgVb)

If everything looks good you can then extract the shadow Appimage.
_Tested on official and alpha._
- `chmod +x ./Shadow.Appimage`
- `./Shadow.Appimage --appimage-extract`

Finally you can run the executable in the new folder squashfs-root
- `./shadow`

If you experience weird reddish colors. Run the following script in order to correct the driver configuration: 
`sudo curl https://raw.githubusercontent.com/NicolasGuilloux/blade-shadow-beta/master/resources/drirc -o /etc/drirc`

You can then move this folder to /opt and make .desktop launcher, or really do anything.
The only issue I can see is a jerky desktop mouse, which can be mitigated by disabling mouse accelaration in windows, and in most games that lock cursors, it should not be a problem.

**Comment by elineda** [comment] 2020-07-08 11:23
Fonctionne avec Fedora 32 et les pilotes propriétaires 440 Nvidia

**Comment by changemenemo** [comment] 2020-07-23 19:50
I didn't try everything right now. Mais si je comprends bien, dans tous les cas il n'y a pas des masses de solutions.
J'ai testé sur un upgrade de 31 à 32. 
L'upgrade s'est fait sans drivers nvidia d'actifs et d'installés, the entire graphic installation have been redone afterwards with the help of [this](https://ask.fedoraproject.org/t/tool-nvidia-easy-automatic-driver-installer-for-fedora-32-workstation-or-above/7279).
everything seems to have been working fine execpt the launcher.
@aarnoud I don't understand you quite well, first you say that everything looks good from here then it the opposite. 
The drivers that the script installed is 440.10
I'm confirming that I'm using a 1080Ti nvidia card with nvidia drivers. 
@elineda Donc tu as réussi à faire fonctionner le launcher du premier coup? Tu as modifié ton fedora sur certains points? 
Quelle version exactement des drivers? 

Pas de message d'erreur dans le terminal au fait puisque je lance l'appimage via ce biais-là. A-t-on des paramètres de logs en terminal pour cette AppImage? 

librtmp est bien installé. Autre chose que je devrais vérifier? C'est pas normal qu'@elineda réussisse à le lancer et pas nous

ni l'app beta ni l'app officielle ne fonctionne. Même erreur pour les deux. Donc en fonction de ce qu@elineda répond on verra si les drivers proprio de nvidia améliore la situation ou pas et alors ça pourrait être dû aux modifications que fait rpmfusion dans ses packages.

**Comment by elineda** [comment] 2020-07-24 07:16
Coucou, 
Alors oui du premier coup, j'ai les drivers nvidia fournis par rpm fusion xorg-x11-drv-nvidia.x86_64 3:440.100-1.fc32, j'ai extrait l'appimage.

Niveau paquet supplementaires j'ai installé ceux ci libva-vdpau-driver libva-utils. Après le reste qui est requis pour faire tourner shadow mais j'ai plus la liste.

Par contre, je tourne sur le spin kde plasma. ça peut peut être jouer.

**Comment by aarnoud** [comment] 2020-07-24 08:15
@boistordu I was answering to someone based on a screenshot during investigation of this issue.

This issue is for "Fedora 32" specific R:1 issue, NVIDIA support as non official for now should now be out of the scope here as it's the same issue on all distributions, open a new issue if needed with all details provided or ask details on discord.

thanks

**Comment by changemenemo** [comment] 2020-07-24 09:11
@elineda exact, avec l'extraction la connexion au shadown fonctionne. J'avais pas pris ce paramètre en compte donc je n'avais point essayé.

**Comment by joker-119** [comment] 2020-08-24 09:09
Here's the thing, I've started experiencing this issue randomly.
I upgraded from F30 to F32 about a month ago.

Shadow was working perfectly fine until it just suddenly started giving me this error.

I literally connected and played for around 7hrs, disconnected from shadow and took a 20min break, came back and have been dealing with this issue since.

I've been playing 8-10+hrs a day on my shadow since upgrading to F32, with 0 issues until suddenly this.
Since there was no reboot of my PC between when the launcher worked, and when it didn't, what's the issue? 
Can't be dependencies. Can't be nvidia driver. Hell I'm not even sure if it's the launcher itself. Literally nothing happened during those 20mins other than taking the movie I was watching on netflix and moving it to my main monitor for 20mins while I ate something.

**Comment by winderickxeli** [comment] 2020-08-28 17:09
Thanks! @ramirocantu That workarround workt fine here:
F32 XFCE

**Comment by NicolasGuilloux** [comment] 2020-10-27 07:50
I'm closing it since everyone seems happy and currently playing games on their Shadow :D Thanks for the participation everyone, you rocks <3

**Closed as completed by NicolasGuilloux** 2020-10-27 07:50 UTC
Labels: bug, AppImage

**Comment by subjectdenied** [comment] 2020-11-04 10:42
fyi: i also had this issue after receiving an update of the nvidia-drivers on f33, i had to reboot for shadow to work again

**Comment by mrwiwi** [comment] 2021-04-09 20:12
Error still poping here in same conditions with Fedora 34, on ryzen 2500u / vega 8.
No issue on manjaro though.

**Comment by subjectdenied** [comment] 2021-04-21 20:02
yes definitly still there, only way around this on F33 and also F34 seems to be to extract the appimage and use the included binary to start the app
