### ISSUE TITLE
Shadow Beta - Fedora 28  - try enqueue failed, queue full

### ISSUE THREAD

**Issue by Bardack66** [NicolasGuilloux/blade-shadow-beta#24] opened 2019-02-13 14:31 UTC
Hi,

I used the "lazy" method (at first) in order to test Shadow on my laptop running on Fedora28.
Result: Shadow start the  welcome screen, the automatic bandwitch check works, etc …

But the moment I click on Start, I go to 3/3 without an issue then the computer completly fails, and I cannot do anything else than rebooting.

Tried all shortcuts proposed, even tried some fancy ones,  just some kind of black  screen or sometimes partial image of my Shadow Windows, with some green on it.

I tried the stable 2.0.4 version AND the nightly build, same shit :(

```
$ vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
failed to open /usr/lib64/dri/hybrid_drv_video.so
Failed to wrapper hybrid_drv_video.so
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)

Logs:
[4624] [2019-02-13 15:22:48.739] [info] vaapi: I-frame

[4620] [2019-02-13 15:22:49.342] [warning] video: try enqueue failed, queue full (queue size: 7)
[4620] [2019-02-13 15:22:49.342] [warning] video: asking for IDR
[4620] [2019-02-13 15:22:49.599] [warning] video: try enqueue failed, queue full (queue size: 7)
[4620] [2019-02-13 15:22:49.599] [warning] video: asking for IDR
```

Thx for any help :)

**Comment by Bardack66** [comment] 2019-02-13 15:04
Well,

I saw on other issues that it might be linked to XFCE 4.12 which I'm using.

I tried on LXCE,Gnome. Now I always see the screen, sometimes with green sometimes not, but not usable and logs:

[2019-02-13 16:01:03.008] [info] (Video) error 1
[2019-02-13 16:01:03.008] [info] (Video) error 1
[2019-02-13 16:01:03.009] [info] (Video) error 1
[2019-02-13 16:01:03.009] [info] (Video) error 1
[2019-02-13 16:01:03.010] [info] (Video) error 1
[2019-02-13 16:01:03.010] [warning] video: try enqueue failed, queue full (queue size: 7)
[2019-02-13 16:01:03.010] [warning] video: asking for IDR
[2019-02-13 16:01:03.010] [info] (Video) error 1
[2019-02-13 16:01:03.011] [info] (Video) error 1
[2019-02-13 16:01:03.011] [info] (Video) error 1
[2019-02-13 16:01:03.012] [info] (Video) error 1
[2019-02-13 16:01:03.012] [info] (Video) error 1
[2019-02-13 16:01:03.013] [info] (Video) error 1
[2019-02-13 16:01:03.013] [info] (Video) error 1
[2019-02-13 16:01:03.014] [info] (Video) error 1
[2019-02-13 16:01:03.015] [info] (Video) error 1
[2019-02-13 16:01:03.015] [info] (Video) error 1

**Comment by NicolasGuilloux** [comment] 2019-02-14 22:03
Hi mate !
Which OS do you use ? As the application were developped for Ubuntu, it can worth the shot to try with Ubuntu 18.04.
Can we have more information about your hardware as well ? Thanks :)

**Comment by Bardack66** [comment] 2019-02-15 08:42
Hoi,

```
[devaf@lp-20140015-linux ~]$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
[devaf@lp-20140015-linux ~]$ lspci
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 0b)
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I218-LM (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
00:1c.3 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 4 (rev e4)
00:1c.4 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 5 (rev e4)
00:1c.5 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 6 (rev e4)
00:1d.0 USB controller: Intel Corporation 8 Series USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
00:1f.2 RAID bus controller: Intel Corporation 82801 Mobile SATA Controller [RAID mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
01:00.0 SD Host controller: O2 Micro, Inc. SD/MMC Card Reader Controller (rev 01)
02:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)
03:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
```

**Comment by NicolasGuilloux** [comment] 2019-02-15 22:01
It seems with a closer look that the VA API fails to use the driver without error. I guess this should be fixed first to finally have the stream.

I don't know Fedora at all, but I guess you should install the i965 drivers for VA API.

By the way, you have 2 GPUs. You re currently trying with the Intel one that does not support h265. But it also meens that the gpu is probably weak for h264 with high quality. Did you try to use the lowest bandwidth?

**Comment by vincent-herlemont** [comment] 2019-03-25 10:51
I have the same problem with arch-linux btw.
```
[4446] [2019-03-25 10:43:49.095] [warning] video: try enqueue failed, queue full (queue size: 7)
[4446] [2019-03-25 10:43:49.095] [warning] video: asking for IDR
[4446] [2019-03-25 10:43:49.132] [warning] video: try enqueue failed, queue full (queue size: 7)
[4446] [2019-03-25 10:43:49.132] [warning] video: asking for IDR
[4446] [2019-03-25 10:43:49.142] [warning] video: try enqueue failed, queue full (queue size: 7)
[4446] [2019-03-25 10:43:49.142] [warning] video: asking for IDR
```
Each enqueue failed induce a huge freeze whatever the window. 

Here my conf graphic controller : 
```00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Lenovo 3rd Gen Core processor Graphics Controller
        Flags: bus master, fast devsel, latency 0, IRQ 29
        Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 5000 [size=64]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [a4] PCI Advanced Features
        Kernel driver in use: i915
        Kernel modules: i915
```
And I use 'i3 windows manager' : 
```
i3 version 4.16.1 (2019-01-27)
```
Bandwidth 5mb/s

**Comment by Pivert** [comment] 2019-04-02 19:57
Hi,

Similar problem here, but with GeForce GT 1030. I also have an APU graphic card that I can't disable (the readeon):
~$ lspci | grep -i vga
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Trinity [Radeon HD 7660D]
01:00.0 VGA compatible controller: NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)

Of course, I use the GeForce.  vainfo:
~$ vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      <unknown profile>               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD

Any help is welcome.

**Comment by aarnoud** [comment] 2019-04-25 06:40
@Pivert GT 1030 has been confirmed to work with your discrete gpu (GT1030)  https://gitlab.com/aar642/libva-vdpau-driver, you just need this patch.

**Comment by aarnoud** [comment] 2019-04-25 06:42
this issue is a duplicate of https://github.com/NicolasGuilloux/blade-shadow-beta/issues/12 but in 2 parts : 

- HD 4000-44000 crashing the machine (unrelated to shadow)
- Graphical glitch at the bottom of the screen (driver or shadow related)

**Closed as completed by aarnoud** 2019-04-25 06:42 UTC
Labels: bug, duplicate, Application
