### ISSUE TITLE
Error R-1: A Shadow app is already running on this device

### ISSUE THREAD

**Issue by b1zzu** [NicolasGuilloux/blade-shadow-beta#78] opened 2020-11-02 10:55 UTC
**Describe the bug**

When I try to start shadow I get this error:

```
A Shadow app is already running on this device
Keep only one Shadow app running and restart this device if the issue remains
Error code: R-1
```

**System**
 - OS: Fedora
 - OS Version: 33
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 4.17.

**Configuration**
 - The user is in input group ? Sorry I don't know what it is
 - The environment uses Xorg ? Yes
 - VA API detects H264 ? And H265 ? Yes

**To Reproduce**
1. Open Shadow
2. CLick on Start Now

**Screenshots**
![image](https://user-images.githubusercontent.com/7964685/97858768-edfdbf00-1cff-11eb-8643-991ffe3e8cd3.png)

**Additional context**

- I tried to reboot the laptop but it didn't fix the issue
- I followed the [setup](https://nicolasguilloux.github.io/blade-shadow-beta/setup) guide to make sure everything is installed correctly but it didn't fix the issue
- I've collected the device debug info here: https://nicolasguilloux.eu/hostbin/2043873617
- If I go to **?**, shutdown shadow, and then start it again it doesn't fix the issue
- If I click on **SERVICE STATUS** it doesn't open anything
- I've tried the **DISPLAY SAFE MODE** but same issue

**Comment by aarnoud** [comment] 2020-11-02 10:58
Duplicate of #55

**Closed as completed by aarnoud** 2020-11-02 10:58 UTC
